apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpapp
  labels:
    app: phpapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpapp
  template:
    metadata:
      labels:
        app: phpapp
    spec:
      containers:
      - name: phpapp
        image: deeptidevadiga/phpapp:v1    # change to your image
        ports:
        - containerPort: 80                # Apache default port
