apiVersion: v1
kind: Service
metadata:
  name: phpapp
  labels:
    app: phpapp
spec:
  type: NodePort
  selector:
    app: phpapp
  ports:
    - port: 80          # service port
      targetPort: 80    # container port
      nodePort: 30082   # you can remove this line to auto-assign
      protocol: TCP
